# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GooglePlacesAutoPop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GooglePlacesAutoPop
  pod 'GooglePlaces'

  target 'GooglePlacesAutoPopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GooglePlacesAutoPopUITests' do
    # Pods for testing
  end

end
